version: "3.7"

services:
  etcd:
    image: cepharum/etcd:latest
    networks:
      - etcd
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 3
    deploy:
      mode: replicated
      replicas: 3

networks:
  etcd:
